export const ConfigList = [
  {
    title: "长赢指数投资",
    source: "且慢",
    host: "ETF拯救世界",
    link: "https://qieman.com/longwin/index/LONG_WIN?appview=1",
    desc: ["基金", "指数", "ETF"],
    id: "long-win",
  },
  {
    title: "ETF网格策略",
    source: "华宝证券",
    host: "ETF拯救世界",
    link: "https://qieman.com/longwin/index/LONG_WIN?appview=1",
    desc: ["ETF", "场内", "网格"],
    id: "etf-grid",
  },
];

export const ConfigDetail = [
  { id: "long-win", code: "000051", name: "华夏沪深300ETF联接A", issue_date: null, source: "长赢指数投资", type: "Fund" },
  { id: "long-win", code: "000071", name: "华夏恒生ETF联接A", issue_date: null, source: "长赢指数投资", type: "Fund" },
  { id: "long-win", code: "000147", name: "易方达高等级信用债A", issue_date: null, source: "长赢指数投资", type: "Fund" },
  { id: "long-win", code: "000216", name: "华安黄金易ETF联接A", issue_date: null, source: "长赢指数投资", type: "Fund" },
  { id: "long-win", code: "000369", name: "广发全球医疗保健(QDII)(人民币)A", issue_date: null, source: "长赢指数投资", type: "Fund" },
  { id: "etf-grid-159920", strategy_id: "etf-grid", code: "159920", name: "恒生ETF" },
];

export const DetailTransaction = [
  {
    sourceId: "etf-grid-159920",
    code: "159920",
    id: 736,
    timestamp: "2020-02-03",
    type: "BUY",
    price: 1.46,
    volume: 6800,
    profit: 0,
    profit_rate: 0,
    is_host: 0,
    source: "ETF拯救世界",
    fee: 0,
  },
  {
    sourceId: "etf-grid-159920",
    code: "159920",
    id: 737,
    timestamp: "2020-02-12",
    type: "SELL",
    price: 1.533,
    volume: -6100,
    profit: 496.4,
    profit_rate: 5,
    is_host: 0,
    source: "ETF拯救世界",
    fee: 0,
  },
  {
    sourceId: "etf-grid-159920",
    code: "159920",
    id: 738,
    timestamp: "2020-03-19",
    type: "BUY",
    price: 1.241,
    volume: 9300,
    profit: 0,
    profit_rate: 0,
    is_host: 0,
    source: "ETF拯救世界",
    fee: 0,
  },
  {
    sourceId: "etf-grid-159920",
    code: "159920",
    id: 739,
    timestamp: "2020-03-26",
    type: "SELL",
    price: 1.314,
    volume: -7900,
    profit: 678.9,
    profit_rate: 5.88,
    is_host: 0,
    source: "ETF拯救世界",
    fee: 0,
  },
  {
    sourceId: "etf-grid-159920",
    code: "159920",
    id: 740,
    timestamp: "2020-03-13",
    type: "BUY",
    price: 1.314,
    volume: 8300,
    profit: 0,
    profit_rate: 0,
    is_host: 0,
    source: "ETF拯救世界",
    fee: 0,
  },
];
