
CREATE TABLE IF NOT EXISTS sync (
    id INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
    user_id VARCHAR(32) NOT NULL COMMENT '用户ID',
    client_id VARCHAR(32) NOT NULL COMMENT '客户端ID',
    data JSON NOT NULL COMMENT 'JSON数据',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT '同步数据';


CREATE TABLE IF NOT EXISTS `transactions` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `code` VARCHAR(191) NOT NULL,  -- 股票代码
    `timestamp` DATE NOT NULL,  -- 成交时间
    `type` VARCHAR(191) NOT NULL,  -- 成交类型
    `price` DOUBLE NULL,  -- 成交价
    `volume` DOUBLE NULL,  -- 成交量
    `profit` DOUBLE NULL,  -- 收益
    `profit_rate` DOUBLE NULL,  -- 收益率
    `source` VARCHAR(191) NULL,  -- 来源 
    `fee` DOUBLE DEFAULT 0 NULL,  -- 手续费
    `is_host` BOOLEAN NOT NULL DEFAULT FALSE,   
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
