
CREATE TABLE IF NOT EXISTS sync (
    id INTEGER PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键',
    user_id VARCHAR(32) NOT NULL COMMENT '用户ID',
    client_id VARCHAR(32) NOT NULL COMMENT '客户端ID',
    data TEXT NOT NULL COMMENT '数据',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '数据入库时间',
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '数据更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
COMMENT '同步数据';
