import type { Metadata } from "next";

import "#styles/global.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import { SidebarInset, SidebarProvider, SidebarTrigger } from "@shadcn/ui/sidebar";
import SideBar from "#components/layout/side-bar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-screen h-screen overflow-x-hidden">
        <NuqsAdapter>
          <SideBar />
          {children}
        </NuqsAdapter>
      </body>
    </html>
  );
}
