import type { Metadata } from "next";

import "#styles/global.css";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import SecurityPanel from "./components/security-panel";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  security,
}: Readonly<{
  children: React.ReactNode;
  security: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex w-screen h-screen overflow-hidden">
        <NuqsAdapter>
          <SecurityPanel />
          <main className="flex-1">{children}</main>
          {security}
        </NuqsAdapter>
      </body>
    </html>
  );
}
